mongo:
  image: biogrid/mongo
  ports:
    - "27017:27017"
# Note: volumes don't work on OS X / VirtualBox yet
#  volumes:
#    - "$PWD/db:/data/db"
mosquitto:
  image: biogrid/mosquitto
  ports:
    - "1883:1883"
node-red:
  image: biogrid/node-red
  ports:
    - "1880:1880"
  volumes:
    - "$PWD/flows:/root/.node-red/flows"
